version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 7
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languag
      
plugins:
  checkstyle:
    enabled: false
    config:
      file: "checkstyle.xml"
  pmd:
    enabled: true
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8